version: '3'

services:
  web:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.client.dev
    #environment:
    #  - export NODE_OPTIONS=--openssl-legacy-provider
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./:/app
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server.dev
    environment:
      - NODE_ENV=development
    ports:
      - '4000:4000'
